INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '7660U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '7600U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '7567U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '7560U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '7500U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '7Y75');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7360U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7300U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7287U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7267U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7260U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7200U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7Y57');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '7Y54');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i3', '7167U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i3', '7130U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i3', '7100U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i3', '7020U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core m3', '7Y32');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core m3', '7Y30');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Pentium', '4415U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Pentium', '4410Y');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Celeron', '3965U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Celeron', '3865U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i3', '8130U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '8650U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i7', '8550U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '8350U');
INSERT INTO `laptop_store`.`cpu` (`cpu_brand_id`, `cpu_modifier`, `cpu_model`) VALUES ('1', 'Core i5', '8250U');
